#!/usr/bin/env bash
# Script to Configure servers !!
sudo apt-get update && sudo apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sudo service nginx start
found="server_name _;"
adding="\n\tadd_header X-Served-By $HOSTNAME;"
sed -i "/$found/a\\$adding" /etc/nginx/sites-available/default

service nginx restart
