#!/usr/bin/env bash
#install HAproxy

apt-get update
apt-get -y install haproxy=1.6.\*
echo "frontend 34.138.157.151
         bind 0:80
         default_backend web-backend
      backend web-backend
         balance roundrobin
	 server web-01 34.139.225.249:80 check
	 server web-02 34.139.242.191:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
