#!/usr/bin/env bash
#Bash script that gives you information about the holbertonschool file.
if [ -e holbertonschool  ]; then
    echo "holbertonschool file exists"
    if [ -f holbertonschool ]; then
        echo "holbertonschool is a regular file"
    fi
    if [ -s holbertonschool  ]; then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
else
    echo "holbertonschool file does not exist"
fi
